(* Generated by Mirage (Sat, 19 Jul 2014 00:35:59 GMT). *)

open Lwt

let _ = Printexc.record_backtrace true

let console1 () =
  Console.connect "0"

module M1 = Unikernel.Main(Console)

let t1 () =
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  M1.start console1

let () =
  OS.Main.run (join [t1 ()])
